owner: rzrabbi
repo: upptime

sites:
  - name: "rzrabbi.com (Personal Site)"
    url: https://rzrabbi.com
  - name: "Rushy Bird (Game)"
    url: https://rzrabbi.itch.io/rushy-bird
  - name: "Rushy Bird (Leaderboard API)"
    url: $RUSHY_BIRD_LEADERBOARD_API_URL
    icon: https://raw.githubusercontent.com/rzrabbi/upptime/master/assets/trophy.svg

status-website:
  theme: night
  baseUrl: /upptime
  metaTags:
    - name: "robots"
      content: "noindex"
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Status page for **rzrabbi's** personal sites and projects."
  introMessage: "This page monitors the real-time uptime and performance of my personal websites, side projects, and APIs."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

i18n:
  footer: " "
